<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Attendance Report</title>
    @php
    use Illuminate\Support\Facades\Auth;
    @endphp
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            line-height: 1.5;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .header h1 {
            color: #c21313;
            margin-bottom: 5px;
        }
        .header p {
            margin: 0;
            color: #666;
        }
        .meta-info {
            margin-bottom: 20px;
            border-bottom: 1px solid #ddd;
            padding-bottom: 10px;
        }
        .meta-info p {
            margin: 5px 0;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .footer {
            margin-top: 20px;
            text-align: center;
            font-size: 10px;
            color: #666;
        }
        .status-present {
            color: green;
        }
        .status-absent {
            color: red;
        }
        .status-excused {
            color: orange;
        }
        .summary {
            margin-top: 20px;
            padding: 10px;
            background-color: #f9f9f9;
            border: 1px solid #ddd;
        }
    </style>
</head>
<body>
    <div class="header">
        <table style="width: 100%; border: none;">
            <tr>
                <td style="width: 20%; text-align: center; border: none; vertical-align: middle;">
                    <div style="font-weight: bold; font-size: 14px; color: #c21313; border: 1px solid #c21313; padding: 10px; border-radius: 5px;">NPC Logo</div>
                </td>
                <td style="width: 60%; text-align: center; border: none;">
                    <div style="font-size: 11px; font-weight: bold; margin-bottom: 2px;">REPUBLIC OF THE PHILIPPINES</div>
                    <div style="font-size: 11px; font-weight: bold; margin-bottom: 5px;">CITY OF NAVOTAS</div>
                    <div style="font-size: 16px; font-weight: bold; margin-bottom: 2px;">NAVOTAS POLYTECHNIC COLLEGE</div>
                    <div style="font-size: 9px; margin-bottom: 5px;">Bangus Street, Corner Apahap Street, North Bay Boulevard South, Navotas City</div>
                    <div style="font-size: 18px; font-weight: bold; margin-bottom: 2px;">ICS ORGANIZATION</div>
                    <div style="font-size: 10px; color: #0000FF;">
                        <a href="mailto:ics@navotaspolytechniccollege.edu.ph">ics@navotaspolytechniccollege.edu.ph</a>
                    </div>
                </td>
                <td style="width: 20%; text-align: center; border: none; vertical-align: middle;">
                    <div style="font-weight: bold; font-size: 14px; color: #c21313; border: 1px solid #c21313; padding: 10px; border-radius: 5px;">ICS Logo</div>
                </td>
            </tr>
        </table>
        <hr style="border: 1px solid #000; margin: 10px 0;">
        <h1 style="text-align: center; color: #c21313; margin: 10px 0;">Attendance Report</h1>
    </div>

    <div class="meta-info">
        <p><strong>Event:</strong> {{ $event->title }}</p>
        <p><strong>Date:</strong> {{ \Carbon\Carbon::parse($event->start_date_time)->format('F d, Y') }}</p>
        <p><strong>Time:</strong> {{ \Carbon\Carbon::parse($event->start_date_time)->format('h:i A') }} - {{ \Carbon\Carbon::parse($event->end_date_time)->format('h:i A') }}</p>
        <p><strong>Location:</strong> {{ $event->location }}</p>
        <p><strong>Report Generated:</strong> {{ $generated_at }}</p>
        <p><strong>Generated By:</strong> {{ $generated_by }}</p>
    </div>

    <h3>Attendance List</h3>

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Name</th>
                <th>Email</th>
                <th>Status</th>
                <th>Comment</th>
            </tr>
        </thead>
        <tbody>
            @forelse($attendance as $index => $record)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $record['name'] }}</td>
                    <td>{{ $record['email'] }}</td>
                    <td class="status-{{ $record['status'] }}">{{ ucfirst($record['status']) }}</td>
                    <td>{{ $record['comment'] ?? '' }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="5" style="text-align: center;">No attendance records found.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="summary">
        <h3>Summary</h3>
        @php
            $presentCount = count(array_filter($attendance, function($record) { return $record['status'] === 'present'; }));
            $absentCount = count(array_filter($attendance, function($record) { return $record['status'] === 'absent'; }));
            $excusedCount = count(array_filter($attendance, function($record) { return $record['status'] === 'excused'; }));
            $totalCount = count($attendance);
            $attendanceRate = $totalCount > 0 ? round(($presentCount / $totalCount) * 100, 2) : 0;
        @endphp
        <p><strong>Total Members:</strong> {{ $totalCount }}</p>
        <p><strong>Present:</strong> {{ $presentCount }} ({{ $attendanceRate }}%)</p>
        <p><strong>Absent:</strong> {{ $absentCount }}</p>
        <p><strong>Excused:</strong> {{ $excusedCount }}</p>
    </div>

    <div class="footer">
        <p>This is an official report generated by the OMCMS system. {{ date('Y-m-d H:i:s') }}</p>
    </div>
</body>
</html>
