<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Membership Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            line-height: 1.5;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .header h1 {
            color: #c21313;
            margin-bottom: 5px;
        }
        .header p {
            margin: 0;
            color: #666;
        }
        .meta-info {
            margin-bottom: 20px;
            border-bottom: 1px solid #ddd;
            padding-bottom: 10px;
        }
        .meta-info p {
            margin: 5px 0;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .footer {
            margin-top: 20px;
            text-align: center;
            font-size: 10px;
            color: #666;
        }
        .status-active {
            color: green;
        }
        .status-pending {
            color: orange;
        }
        .status-inactive {
            color: red;
        }
        .summary {
            margin-top: 20px;
            padding: 10px;
            background-color: #f9f9f9;
            border: 1px solid #ddd;
        }
        .chart-container {
            width: 100%;
            margin: 20px 0;
            text-align: center;
        }
        .chart {
            width: 100%;
            height: 200px;
            border: 1px solid #ddd;
            padding: 10px;
            box-sizing: border-box;
        }
    </style>
</head>
<body>
    <div class="header">
        <table style="width: 100%; border: none;">
            <tr>
                <td style="width: 20%; text-align: center; border: none; vertical-align: middle;">
                    <div style="font-weight: bold; font-size: 14px; color: #c21313; border: 1px solid #c21313; padding: 10px; border-radius: 5px;">NPC Logo</div>
                </td>
                <td style="width: 60%; text-align: center; border: none;">
                    <div style="font-size: 11px; font-weight: bold; margin-bottom: 2px;">REPUBLIC OF THE PHILIPPINES</div>
                    <div style="font-size: 11px; font-weight: bold; margin-bottom: 5px;">CITY OF NAVOTAS</div>
                    <div style="font-size: 16px; font-weight: bold; margin-bottom: 2px;">NAVOTAS POLYTECHNIC COLLEGE</div>
                    <div style="font-size: 9px; margin-bottom: 5px;">Bangus Street, Corner Apahap Street, North Bay Boulevard South, Navotas City</div>
                    <div style="font-size: 18px; font-weight: bold; margin-bottom: 2px;">ICS ORGANIZATION</div>
                    <div style="font-size: 10px; color: #0000FF;">
                        <a href="mailto:ics@navotaspolytechniccollege.edu.ph">ics@navotaspolytechniccollege.edu.ph</a>
                    </div>
                </td>
                <td style="width: 20%; text-align: center; border: none; vertical-align: middle;">
                    <div style="font-weight: bold; font-size: 14px; color: #c21313; border: 1px solid #c21313; padding: 10px; border-radius: 5px;">ICS Logo</div>
                </td>
            </tr>
        </table>
        <hr style="border: 1px solid #000; margin: 10px 0;">
        <h1 style="text-align: center; color: #c21313; margin: 10px 0;">Membership Report</h1>
    </div>

    <div class="meta-info">
        <p><strong>Status Filter:</strong> {{ $status }}</p>
        <p><strong>Role Filter:</strong> {{ $role }}</p>
        <p><strong>Join Date Range:</strong> {{ $join_date_from }} to {{ $join_date_to }}</p>
        <p><strong>Report Generated:</strong> {{ $generated_at }}</p>
        <p><strong>Generated By:</strong> {{ $generated_by }}</p>
    </div>

    <div class="summary">
        <h3>Membership Summary</h3>
        <table>
            <tr>
                <th>Category</th>
                <th>Count</th>
                <th>Percentage</th>
            </tr>
            <tr>
                <td>Total Members</td>
                <td>{{ $total_members }}</td>
                <td>100%</td>
            </tr>
            <tr>
                <td>Active Members</td>
                <td>{{ $active_members }}</td>
                <td>{{ $total_members > 0 ? round(($active_members / $total_members) * 100, 2) : 0 }}%</td>
            </tr>
            <tr>
                <td>Pending Members</td>
                <td>{{ $pending_members }}</td>
                <td>{{ $total_members > 0 ? round(($pending_members / $total_members) * 100, 2) : 0 }}%</td>
            </tr>
            <tr>
                <td>Inactive Members</td>
                <td>{{ $inactive_members }}</td>
                <td>{{ $total_members > 0 ? round(($inactive_members / $total_members) * 100, 2) : 0 }}%</td>
            </tr>
            <tr>
                <td>Admin Users</td>
                <td>{{ $admin_count }}</td>
                <td>{{ $total_members > 0 ? round(($admin_count / $total_members) * 100, 2) : 0 }}%</td>
            </tr>
            <tr>
                <td>Regular Members</td>
                <td>{{ $regular_member_count }}</td>
                <td>{{ $total_members > 0 ? round(($regular_member_count / $total_members) * 100, 2) : 0 }}%</td>
            </tr>
        </table>
    </div>

    <h3>Member List</h3>

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>ID</th>
                <th>Name</th>
                <th>Email</th>
                <th>Status</th>
                <th>Role</th>
                <th>Join Date</th>
            </tr>
        </thead>
        <tbody>
            @forelse($members as $index => $member)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $member->id }}</td>
                    <td>{{ $member->firstname }} {{ $member->lastname }}</td>
                    <td>{{ $member->email }}</td>
                    <td class="status-{{ $member->status }}">{{ ucfirst($member->status) }}</td>
                    <td>{{ in_array($member->user_role, ['superadmin', 'officer']) ? 'Admin' : 'Member' }}</td>
                    <td>{{ $member->created_at->format('Y-m-d') }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="7" style="text-align: center;">No members found matching the criteria.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        <p>This is an official report generated by the OMCMS system. {{ date('Y-m-d H:i:s') }}</p>
    </div>
</body>
</html>
