<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Payment Report</title>
    @php
    use Illuminate\Support\Facades\Auth;
    @endphp
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            line-height: 1.5;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .header h1 {
            color: #c21313;
            margin-bottom: 5px;
        }
        .header p {
            margin: 0;
            color: #666;
        }
        .meta-info {
            margin-bottom: 20px;
            border-bottom: 1px solid #ddd;
            padding-bottom: 10px;
        }
        .meta-info p {
            margin: 5px 0;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .footer {
            margin-top: 20px;
            text-align: center;
            font-size: 10px;
            color: #666;
        }
        .status-Paid {
            color: green;
        }
        .status-Pending {
            color: orange;
        }
        .status-Rejected {
            color: red;
        }
        .summary {
            margin-top: 20px;
            padding: 10px;
            background-color: #f9f9f9;
            border: 1px solid #ddd;
        }
        .amount {
            text-align: right;
        }
    </style>
</head>
<body>
    <div class="header">
        <table style="width: 100%; border: none;">
            <tr>
                <td style="width: 20%; text-align: center; border: none; vertical-align: middle;">
                    <div style="font-weight: bold; font-size: 14px; color: #c21313; border: 1px solid #c21313; padding: 10px; border-radius: 5px;">NPC Logo</div>
                </td>
                <td style="width: 60%; text-align: center; border: none;">
                    <div style="font-size: 11px; font-weight: bold; margin-bottom: 2px;">REPUBLIC OF THE PHILIPPINES</div>
                    <div style="font-size: 11px; font-weight: bold; margin-bottom: 5px;">CITY OF NAVOTAS</div>
                    <div style="font-size: 16px; font-weight: bold; margin-bottom: 2px;">NAVOTAS POLYTECHNIC COLLEGE</div>
                    <div style="font-size: 9px; margin-bottom: 5px;">Bangus Street, Corner Apahap Street, North Bay Boulevard South, Navotas City</div>
                    <div style="font-size: 18px; font-weight: bold; margin-bottom: 2px;">ICS ORGANIZATION</div>
                    <div style="font-size: 10px; color: #0000FF;">
                        <a href="mailto:ics@navotaspolytechniccollege.edu.ph">ics@navotaspolytechniccollege.edu.ph</a>
                    </div>
                </td>
                <td style="width: 20%; text-align: center; border: none; vertical-align: middle;">
                    <div style="font-weight: bold; font-size: 14px; color: #c21313; border: 1px solid #c21313; padding: 10px; border-radius: 5px;">ICS Logo</div>
                </td>
            </tr>
        </table>
        <hr style="border: 1px solid #000; margin: 10px 0;">
        <h1 style="text-align: center; color: #c21313; margin: 10px 0;">Payment Report</h1>
    </div>

    <div class="meta-info">
        <p><strong>Date Range:</strong> {{ $date_from }} to {{ $date_to }}</p>
        <p><strong>Payment Method:</strong> {{ $payment_method }}</p>
        <p><strong>Payment Status:</strong> {{ $payment_status }}</p>
        <p><strong>Purpose:</strong> {{ $purpose }}</p>
        <p><strong>Report Generated:</strong> {{ $generated_at }}</p>
        <p><strong>Generated By:</strong> {{ $generated_by }}</p>
    </div>

    <h3>Payment List</h3>

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>ID</th>
                <th>Email</th>
                <th>Method</th>
                <th>Purpose</th>
                <th>Status</th>
                <th>Date</th>
                <th>Amount</th>
            </tr>
        </thead>
        <tbody>
            @forelse($payments as $index => $payment)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $payment['id'] }}</td>
                    <td>{{ $payment['email'] }}</td>
                    <td>{{ $payment['method'] }}</td>
                    <td>{{ $payment['purpose'] }}</td>
                    <td class="status-{{ $payment['status'] }}">{{ $payment['status'] }}</td>
                    <td>{{ $payment['date'] }}</td>
                    <td class="amount">₱{{ number_format($payment['amount'], 2) }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="8" style="text-align: center;">No payment records found.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="summary">
        <h3>Financial Summary</h3>
        <table>
            <tr>
                <th>Description</th>
                <th>Amount</th>
            </tr>
            <tr>
                <td>Total Amount</td>
                <td class="amount">₱{{ number_format($total_amount, 2) }}</td>
            </tr>
            <tr>
                <td>Total Paid</td>
                <td class="amount">₱{{ number_format($total_paid, 2) }}</td>
            </tr>
            <tr>
                <td>Total Pending</td>
                <td class="amount">₱{{ number_format($total_pending, 2) }}</td>
            </tr>
        </table>

        @php
            $methodCounts = [];
            $purposeCounts = [];

            foreach ($payments as $payment) {
                // Count by method
                if (!isset($methodCounts[$payment['method']])) {
                    $methodCounts[$payment['method']] = [
                        'count' => 0,
                        'amount' => 0
                    ];
                }
                $methodCounts[$payment['method']]['count']++;
                $methodCounts[$payment['method']]['amount'] += $payment['amount'];

                // Count by purpose
                if (!isset($purposeCounts[$payment['purpose']])) {
                    $purposeCounts[$payment['purpose']] = [
                        'count' => 0,
                        'amount' => 0
                    ];
                }
                $purposeCounts[$payment['purpose']]['count']++;
                $purposeCounts[$payment['purpose']]['amount'] += $payment['amount'];
            }
        @endphp

        <h4>Breakdown by Payment Method</h4>
        <table>
            <tr>
                <th>Method</th>
                <th>Count</th>
                <th>Amount</th>
            </tr>
            @foreach($methodCounts as $method => $data)
                <tr>
                    <td>{{ $method }}</td>
                    <td>{{ $data['count'] }}</td>
                    <td class="amount">₱{{ number_format($data['amount'], 2) }}</td>
                </tr>
            @endforeach
        </table>

        <h4>Breakdown by Purpose</h4>
        <table>
            <tr>
                <th>Purpose</th>
                <th>Count</th>
                <th>Amount</th>
            </tr>
            @foreach($purposeCounts as $purpose => $data)
                <tr>
                    <td>{{ $purpose }}</td>
                    <td>{{ $data['count'] }}</td>
                    <td class="amount">₱{{ number_format($data['amount'], 2) }}</td>
                </tr>
            @endforeach
        </table>
    </div>

    <div class="footer">
        <p>This is an official report generated by the OMCMS system. {{ date('Y-m-d H:i:s') }}</p>
    </div>
</body>
</html>
